### ISSUE TITLE
Feature request: customise login with button

### ISSUE THREAD

**Issue by mehdibo** [zorn-v/nextcloud-social-login#231]
It would be great if there was a possibility to customise custom oauth2 provider's button style (icon, text color & on hover, bg color & on hover)

**Comment by daniel-richter** [comment]
You can install the [Custom CSS App](https://apps.nextcloud.com/apps/theming_customcss) and change the styles:
``` css
#alternative-logins a.button[href*="/sociallogin/oauth/GitHub"] { background-color:red }
```
