### ISSUE TITLE
Clean up after unlinking a (discord) account, the database is not correct

### ISSUE THREAD

**Issue by iFuzzle** [zorn-v/nextcloud-social-login#442]
``After unlinking my account from discord I tried to link it again and was not able to.
Apparently some clean up is not working correctly.

---

### How to reproduce:

MIGHT be part of the cause:
- Configure Discord via default providers.
- Create a new account from Nextcloud login page via Discord Button.
- Remove that user via nextclouds user panel.

Break the linking:
- Login to your existing nextcloud account
- via personal preferences link discord to your nextcloud account
- unlink discord account (click the x)
- try linking discord again

Issue(s):
- I ran into a 401 unaothorized issue displayed on Nextclouds
- I ran into "this account is already linked" issue on Nextcloud

Mitigation:
I removed my App from the know discord apps, but that alone did not fix the issue.
I was finaly able to fix my issue by deleting a line in the database, that had a `discord-[your numerical discord ID]` uid in the table `oc_users`
``DELETE FROM oc_users WHERE uid="discord-xxxx";`` 

---

I did **not** fully **test the reproduction** steps again, so please have a look yourself if you try to reproduce :)

_Systeminformation:_
```yaml
date: '19-12-2023'
host: 'Docker version 24.0.7, build afdd53b (on a Raspberry Pi Model 4 B)'
nextcloud-image: 'apache'
nextcloud-version: '28.0'
database: 'mariaDB'
database-image: 'mariadb:10.6'
database-version: 'mysql  Ver 15.1 Distrib 10.6.16-MariaDB, for debian-linux-gnu (aarch64) using readline 5.2'
redis-image: 'latest:alpine'
sociallogin-version: 5.6.0
```
for the configuration of the sociallogin app I only ticked the boxes 2-5 (create user as deactivated, allow users to link social login with existing accounts, block new user creation if the email address is known(!), refresh the user profile picture with every login)

Let me know if you need further details :)
